### ISSUE TITLE
Add a flag to ignore initially failing test

### ISSUE THREAD

**Issue by langston-barrett** [renatahodovan/picireny#21]
I'd like to benchmark picireny against other test case reduction tools. There are a few "interestingness tests" I will use as part of this benchmark, one of which is essentially `false`, i.e., the test that never passes (the idea is to get at the worst-case execution time). [Halfempty](https://github.com/googleprojectzero/halfempty) provides a `--noverify` flag, perhaps picireny could do something similar?

For reference, here's the end of the stderr of picireny when run on such a test at the moment:
```
    assert self._test_config(config, ('r%d' % run, 'assert')) is Outcome.FAIL
AssertionError
```

**Comment by renatahodovan** [comment]
Hi @langston-barrett 

These asserts are executed at the beginning of every run/iteration and aim to verify if the initial or the current version of the test case under reduction still reproduces the interestingness property. However, these are just sanity checks and are easy to disable them by settings Python's standard `PYTHONOPTIMIZE` environment variable to `1`:

```bash
PYTHONOPTIMIZE=1 picireny -t test.sh ...
```

If you use this setup though for benchmarking, then don't forget to set this variable for the other tests too, since it'll opt out a SUT call at every cycle and the results won't be comparable otherwise.

**Comment by langston-barrett** [comment]
@renatahodovan Awesome, thanks for the tip! I'll be sure to set `PYTHONOPTIMIZE` whenever benchmarking picireny.
